/**
 * Bundle Electron main + preload for pkg-runner,
 * and copy shared fonts into ui/ for file:// loading.
 */
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontsPkg = path.join(root, 'vendor', 'fonts');
const fontsOut = path.join(root, 'ui', 'fonts');
const distOut = path.join(root, 'dist');
const dev = process.argv.includes('--dev');

fs.rmSync(distOut, { recursive: true, force: true });
fs.mkdirSync(distOut, { recursive: true });

const shared = {
  bundle: true,
  platform: 'node',
  target: 'node20',
  sourcemap: dev,
  minify: !dev,
  packages: 'bundle',
  external: ['electron', 'node-pty'],
};

await esbuild.build({
  ...shared,
  entryPoints: [path.join(root, 'src/main.ts')],
  outfile: path.join(distOut, 'main.js'),
  format: 'esm',
});

/** Preload must be .cjs — package.json "type":"module" makes .js load as ESM and breaks preload. */
await esbuild.build({
  ...shared,
  entryPoints: [path.join(root, 'src/preload.ts')],
  outdir: distOut,
  outbase: path.join(root, 'src'),
  format: 'cjs',
  outExtension: { '.js': '.cjs' },
});

/** Copy xterm browser assets into ui/vendor for vanilla fallback (file://). */
const require = (await import('node:module')).createRequire(import.meta.url);
const vendorOut = path.join(root, 'ui', 'vendor');
fs.rmSync(vendorOut, { recursive: true, force: true });
fs.mkdirSync(vendorOut, { recursive: true });
// xterm lives on @pkg-runner/web in the monorepo
const webRequire = (await import('node:module')).createRequire(
  path.join(root, '..', 'web', 'package.json'),
);
const xtermRoot = path.dirname(webRequire.resolve('@xterm/xterm/package.json'));
const fitRoot = path.dirname(webRequire.resolve('@xterm/addon-fit/package.json'));
fs.copyFileSync(path.join(xtermRoot, 'css', 'xterm.css'), path.join(vendorOut, 'xterm.css'));
const xtermJs = ['lib/xterm.min.js', 'lib/xterm.js']
  .map((rel) => path.join(xtermRoot, rel))
  .find((p) => fs.existsSync(p));
if (!xtermJs) throw new Error('xterm.js not found');
fs.copyFileSync(xtermJs, path.join(vendorOut, 'xterm.js'));
fs.copyFileSync(path.join(fitRoot, 'lib', 'addon-fit.js'), path.join(vendorOut, 'addon-fit.js'));

/** 只打包实际用到的字重，避免整套 JetBrains Mono（约 1.5MB → ~0.3MB） */
const FONT_FACES = [
  { file: 'JetBrainsMono-Regular.woff2', weight: 400, style: 'normal' },
  { file: 'JetBrainsMono-SemiBold.woff2', weight: 600, style: 'normal' },
  { file: 'JetBrainsMono-Bold.woff2', weight: 700, style: 'normal' },
];

fs.rmSync(fontsOut, { recursive: true, force: true });
fs.mkdirSync(path.join(fontsOut, 'files', 'jetbrains-mono'), { recursive: true });
const fontCss = [
  '/* JetBrains Mono (subset) — SIL OFL 1.1 */',
  ...FONT_FACES.flatMap(({ file, weight, style }) => [
    '@font-face {',
    `  font-family: 'JetBrains Mono';`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url('./files/jetbrains-mono/${file}') format('woff2');`,
    '}',
    '',
  ]),
].join('\n');
fs.writeFileSync(path.join(fontsOut, 'jetbrains-mono.css'), fontCss, 'utf8');
for (const { file } of FONT_FACES) {
  fs.copyFileSync(
    path.join(fontsPkg, 'files', 'jetbrains-mono', file),
    path.join(fontsOut, 'files', 'jetbrains-mono', file),
  );
}

const catalog = await import(pathToFileURL(path.join(fontsPkg, 'catalog.js')).href);
const catalogOut = path.join(root, 'ui', 'fonts-catalog.js');
fs.writeFileSync(
  catalogOut,
  `/* auto-generated by scripts/build-main.mjs — do not edit */
window.PkgFonts = {
  FONT_PRESETS: ${JSON.stringify(catalog.FONT_PRESETS, null, 2)},
  DEFAULT_FONT_ID: ${JSON.stringify(catalog.DEFAULT_FONT_ID)},
  applyDocumentFonts(opts) {
    const rootEl = document.documentElement;
    const resolve = (presets, id, fallback) => {
      const hit = presets.find((p) => p.id === id);
      return (hit || presets.find((p) => p.id === fallback) || presets[0]).stack;
    };
    const id = opts && (opts.fontId || opts.monoFontId || opts.uiFontId);
    const stack = resolve(this.FONT_PRESETS, id, this.DEFAULT_FONT_ID);
    rootEl.style.setProperty('--font', stack);
    rootEl.style.setProperty('--sans', stack);
    rootEl.style.setProperty('--mono', stack);
  },
};
`,
  'utf8',
);

console.log('[runner] esbuild ok; fonts/vendor trimmed');
